### ISSUE TITLE
Cannot open correlation.csv file?

### ISSUE THREAD

**Issue by XueaoZHENG** [susbo/concur#2]
Thanks a lot for providing this software to A-site counting;
I tried a lot of software, this is very user-friendly. 
But meet an issue with the analysis of the dataset (Nedialkova and Leidel, 2015).

Here is my code:
System: Ubuntu 20.04 LTS

Input:
 concur perl concur.pl -w -i ../geno_bam/SRR1944912.1_1.fastq.gz.sam.bam.rm.bam.long.bam -g sc3 -o WT_1
Running CONCUR v1.0

Output:
#####  General options  #######
Input file: ../geno_bam/SRR1944912.1_1.fastq.gz.sam.bam.rm.bam.long.bam
Genome: sc3
Output folder: WT_1
Output file name: SRR1944912.1_1.fastq.gz.sam.rm.bam.long.bam
Run without R: TRUE
#####  Analysis options  ######
Fragment size range tested: 20-50
Minimum number of reads: 1000
Outlier removal filter [2.2.3]: 0.5
###############################
[Step 1/10] Mapping genomic reads to transcripts...
[Step 2/10] Calculating periodicity...
[Step 3/10] Predicting offset per read set...
[Step 4/10] Calculating codon frequency per read set...
[Step 5/10] Calculating codon frequency (step 2) per read set...
[Step 7/10] Calculating correlations between read sets...

Cannot open SRR1944912.1_1.fastq.gz.sam.rm.bam.long.bam.correlation.csv

**Comment by XueaoZHENG** [comment]
PS: this file SRR1944912.1_1.fastq.gz.sam.rm.bam.long.bam.correlation.csv is empty in the temp folder.

**Comment by susbo** [comment]
Hi XueaoZHENG, 

Thank you for your interest in using CONCUR.

Does it work if you run it without the "-w" (without R) flag? The intention was that it should be possible to skip the visualization steps that require R to be installed, but it looks that those steps are currently needed to create the correlation table...

I will try to get an update done in the coming days that resolves this dependency, but for now I think running it without "-w" should resolve the issue.

Best,
Susanne

**Comment by XueaoZHENG** [comment]
Hi, Susanne!

I solved this problem yesterday by changing to use another server.
This problem is likely caused by the R or R packages. 
Another demand is the ape-site matrix of each gene or even each read (it looks they are not in the temp file), which will make the downstream analysis much easier!

Waiting for your update!!!

All the best!
Xueao

**Comment by susbo** [comment]
This should be solved today with v1.1.1-beta.
